name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        buildtype: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.buildtype }}
      CMAKE_PRESET: ${{ matrix.buildtype == 'Debug' && 'clang-tidy' || 'ninja' }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # Find the clang-tidy bundled with MSVC
    - name: Add clang-tidy to PATH
      if: env.BUILD_TYPE == 'Debug'
      uses: Lectem/vswhere@v1.0
      with: {file: 'VC\Tools\Llvm\bin\clang-tidy.exe'}
    
    # We need to start cmake from vcvarsall env so that Ninja will pick MSVC
    - uses: ilammy/msvc-dev-cmd@v1
      with: {arch: x86}

    - name: CMake configure and build
      run: |
        cmake --preset ${{env.CMAKE_PRESET}}
        cmake --build --preset ${{env.CMAKE_PRESET}} --config ${{env.BUILD_TYPE}}

    - name: Test
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --preset ${{env.CMAKE_PRESET}} -C ${{env.BUILD_TYPE}}

    - name: Install
      if: env.BUILD_TYPE == 'Release'
      run: cmake --build --preset ${{env.CMAKE_PRESET}} --config ${{env.BUILD_TYPE}} --target install

    - name: Artifact
      if: env.BUILD_TYPE == 'Release'
      uses: actions/upload-artifact@v2.2.1
      with:
        path:  ${{runner.workspace}}/install/*
