name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        buildtype: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.buildtype }}
      CMAKE_PRESET: VS2022

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: CMake configure and build
      run: |
        cmake --preset ${{env.CMAKE_PRESET}}
        cmake --build --preset ${{env.CMAKE_PRESET}} --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --preset ${{env.CMAKE_PRESET}} -C ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --build --preset ${{env.CMAKE_PRESET}} --config ${{env.BUILD_TYPE}} --target install

    - name: Artifact
      if: env.BUILD_TYPE == 'Release'
      uses: actions/upload-artifact@v2.2.1
      with:
        path:  ${{runner.workspace}}/install/*
